### ISSUE TITLE
Finding charts and visibility plot

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/astro-log#2]
Finding charts could be super helpful for looking up new objects for the first time

- [x] Visibility plot (single object) - #26
- [x] Visibility plot (multiple objects) - #27
- [x] Finding chart with custom radius - #28
- [ ] The above with custom location (might require login, as to not getting too many requests)

**Comment by DanielAndreasen** [comment]
For finding chart: https://learn.astropy.org/tutorials/conesearch.html
